"""AI layer (Nemotron via NVIDIA API by default; Anthropic optional) — two
jobs:

1. RFP Analyst pass (ingest-time, OPEN items): extract structured JSON from
   the 470 + attached RFP text, plus a 2-3 sentence fit rationale.
2. Response Generator pass (on demand): drafts the narrative sections of a
   response. Pricing is NEVER generated by the model — the pricing table is
   built deterministically in pricing.py from the uploaded price list, and
   anything not present in uploaded company data must be [NEEDS INPUT].
"""
import json
import logging
import re

from . import config, db

log = logging.getLogger(__name__)

ANALYST_SYSTEM = """You are an E-Rate RFP analyst for Mission Telecom, a \
telecom/wireless provider selling internet access, WAN, wireless data, Wi-Fi \
and internal connections to K-12 schools and libraries. Extract facts ONLY \
from the provided documents. Never guess; use null when a fact is absent."""

ANALYST_SCHEMA_HINT = """Return ONLY a JSON object with exactly these keys:
{
 "issuing_entity": str|null,
 "state": str|null,
 "services_requested": [{"service": str, "quantity": str|null, "bandwidth": str|null}],
 "contract_term_years": number|null,
 "mandatory_requirements": [str],
 "evaluation_criteria": [{"criterion": str, "weight": str|null}],
 "price_primary_factor": bool|null,
 "question_deadline": str|null,
 "submission_method": str|null,
 "submission_deadline": str|null,
 "disqualifiers": [str],
 "rationale": str
}
"rationale" is a 2-3 sentence assessment of Mission Telecom's fit: what they \
asked for, deal attractiveness, and any bid barriers."""


def _chat(system: str, user: str, max_tokens: int = 2000) -> str | None:
    """One chat completion via the configured provider (Nemotron by default,
    Anthropic as alternative). Returns the text or None on failure/no key."""
    provider = config.llm_provider()
    if provider == "nemotron":
        return _chat_nemotron(system, user, max_tokens)
    if provider == "anthropic":
        return _chat_anthropic(system, user, max_tokens)
    return None


def _chat_nemotron(system: str, user: str, max_tokens: int) -> str | None:
    """NVIDIA API (OpenAI-compatible). /no_think keeps Nemotron in direct-
    answer mode so responses are pure JSON without reasoning preambles."""
    import httpx
    try:
        resp = httpx.post(
            f"{config.NEMOTRON_BASE_URL}/chat/completions",
            headers={"Authorization": f"Bearer {config.NEMOTRON_API_KEY}",
                     "Content-Type": "application/json"},
            json={
                "model": config.NEMOTRON_MODEL,
                "messages": [
                    {"role": "system", "content": f"/no_think {system}"},
                    {"role": "user", "content": user},
                ],
                # Nemotron spends tokens on a reasoning phase (returned
                # separately as reasoning_content) before the answer; without
                # headroom the answer gets truncated away entirely.
                "max_tokens": max(max_tokens * 4, 8000),
                "temperature": 0.2,
            },
            timeout=180,
        )
        resp.raise_for_status()
        text = resp.json()["choices"][0]["message"]["content"] or ""
        # strip any reasoning block defensively
        text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
        return text.strip()
    except Exception as e:
        log.warning("nemotron request failed: %s", e)
        return None


def _chat_anthropic(system: str, user: str, max_tokens: int) -> str | None:
    import anthropic
    try:
        client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
        msg = client.messages.create(
            model=config.ANTHROPIC_MODEL, max_tokens=max_tokens,
            system=system, messages=[{"role": "user", "content": user}])
        return msg.content[0].text
    except Exception as e:
        log.warning("anthropic request failed: %s", e)
        return None


def analyze_rfp(application_number: str, force: bool = False) -> dict | None:
    """Run the analyst pass for one RFP; stores JSON in rfps.analysis and the
    AI rationale in score_rationale. Returns the analysis or None."""
    if config.llm_provider() is None:
        log.info("no AI provider key set; skipping analyst pass")
        return None
    with db.closing_conn() as conn:
        row = conn.execute("SELECT * FROM rfps WHERE application_number=?",
                           (application_number,)).fetchone()
    if row is None:
        return None
    if row["analysis"] and not force:
        return json.loads(row["analysis"])

    context = _build_context(dict(row))
    text = _chat(ANALYST_SYSTEM, f"{ANALYST_SCHEMA_HINT}\n\n{context}",
                 max_tokens=2000)
    analysis = _parse_json(text) if text else None
    if not analysis:
        log.warning("analyst pass failed for %s", application_number)
        return None
    with db.closing_conn() as conn:
        conn.execute(
            "UPDATE rfps SET analysis=?, score_rationale=? "
            "WHERE application_number=?",
            (json.dumps(analysis), analysis.get("rationale"),
             application_number))
        conn.commit()
    return analysis


def analyze_open_batch(limit: int = 25) -> int:
    """Analyst pass for OPEN relevant items not yet analyzed."""
    from . import status as status_mod
    if config.llm_provider() is None:
        return 0
    with db.closing_conn() as conn:
        rows = conn.execute(
            "SELECT application_number, certified_date, allowable_contract_date"
            " FROM rfps WHERE relevant=1 AND analysis IS NULL").fetchall()
    done = 0
    for r in rows:
        if done >= limit:
            break
        st, _ = status_mod.compute_status(
            status_mod.parse_usac_date(r["certified_date"]),
            status_mod.parse_usac_date(r["allowable_contract_date"]))
        if st == status_mod.CLOSED:
            continue
        if analyze_rfp(r["application_number"]):
            done += 1
    if done:
        from . import scoring
        scoring.score_all(rescore=True)  # analysis feeds winnability/strategic
    return done


def draft_narratives(row: dict, analysis: dict, profile: dict) -> dict:
    """Cover letter + compliance-matrix responses. Uses ONLY profile data;
    the model is instructed to emit [NEEDS INPUT] for anything missing, and we
    also enforce placeholders in respond.py."""
    requirements = analysis.get("mandatory_requirements") or []
    if config.llm_provider() is None:
        return {
            "cover_letter": "[NEEDS INPUT: cover letter — set "
                            "NEMOTRON_API_KEY or ANTHROPIC_API_KEY to "
                            "auto-draft]",
            "compliance": [{"requirement": req,
                            "response": "[NEEDS INPUT]",
                            "compliance": "REVIEW"} for req in requirements],
        }
    system = (
        "You draft E-Rate RFP responses for Mission Telecom. HARD RULES: "
        "(1) Use ONLY facts present in the COMPANY PROFILE JSON. "
        "(2) If a fact is not in the profile (a certification, reference, "
        "insurance detail, capability), write exactly [NEEDS INPUT] in its "
        "place — never invent, never estimate. "
        "(3) Never state prices or dollar amounts anywhere. "
        "(4) Mark compliance as COMPLY only when the profile clearly supports "
        "it; otherwise EXCEPTION or REVIEW.")
    user = (
        "COMPANY PROFILE JSON:\n" + json.dumps(profile, indent=2) +
        "\n\nRFP ANALYSIS JSON:\n" + json.dumps(analysis, indent=2) +
        "\n\nRFP CONTACT: " + json.dumps({
            "name": row.get("contact_name"), "email": row.get("contact_email"),
            "entity": row.get("billed_entity_name"), "state": row.get("state"),
        }) +
        "\n\nReturn ONLY JSON: {\"cover_letter\": str (a professional cover "
        "letter addressed to the RFP contact, <=350 words), \"compliance\": "
        "[{\"requirement\": str, \"response\": str, \"compliance\": "
        "\"COMPLY\"|\"EXCEPTION\"|\"REVIEW\"}] — one entry per mandatory "
        "requirement listed in the analysis.}")
    text = _chat(system, user, max_tokens=4000)
    out = _parse_json(text) if text else None
    if out and isinstance(out.get("compliance"), list):
        return out
    log.warning("response generator failed or returned malformed output")
    return {
        "cover_letter": "[NEEDS INPUT: cover letter draft failed]",
        "compliance": [{"requirement": req, "response": "[NEEDS INPUT]",
                        "compliance": "REVIEW"} for req in requirements],
    }


def _build_context(row: dict) -> str:
    parts = [
        "=== FORM 470 STRUCTURED DATA ===",
        json.dumps({k: row.get(k) for k in (
            "application_number", "form_nickname", "funding_year",
            "billed_entity_name", "applicant_type", "state", "city",
            "certified_date", "allowable_contract_date", "service_types",
            "functions", "cat1_description", "cat2_description",
            "contact_name", "contact_email")}, indent=1),
    ]
    if row.get("doc_text"):
        parts += ["=== ATTACHED DOCUMENT TEXT (Form 470 PDF and/or RFP) ===",
                  row["doc_text"][:150_000]]
    else:
        parts += ["(No attached documents; analyze the structured data only.)"]
    return "\n".join(parts)


def _parse_json(text: str) -> dict | None:
    text = text.strip()
    if text.startswith("```"):
        text = text.strip("`")
        if text.startswith("json"):
            text = text[4:]
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end == -1:
        return None
    try:
        return json.loads(text[start:end + 1])
    except json.JSONDecodeError:
        pass
    # fallback: find any balanced JSON object (stray braces in prose)
    decoder = json.JSONDecoder()
    idx = start
    while idx != -1:
        try:
            obj, _ = decoder.raw_decode(text[idx:])
            if isinstance(obj, dict):
                return obj
        except json.JSONDecodeError:
            pass
        idx = text.find("{", idx + 1)
    return None
